services:
  dineeasy-microservices:
    image: dineeasy-microservices
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
      - "5001:5001"
      - "5002:5002"
      - "5003:5003"
      - "5004:5004"
      - "5005:5005"
      - "5006:5006"
        
